name: "Dependabot auto merge"

on:
  pull_request:
    branches:
      - "*"
permissions:
  contents: write
  pull-requests: write
  id-token: write
jobs:
  dependabot-auto-merge:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: approve Dependabot PR
        run: |
          gh pr review --approve ${{ github.event.pull_request.html_url }} --body "Auto approved by CI"
      - name: Enable auto-merge for Dependabot PRs
        run: |
          gh pr merge --auto --squash ${{ github.event.pull_request.html_url }}